name: Refresh logos workflow

on: push

jobs:
  my-job:
    name: Update surge
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: '${{ secrets.surge_url }}'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
